rspec_project/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :index]
  resource :session, only: [:new, :create, :destroy]
end

rspec_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rspec_project/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true  
  validates :password, length: {minimum: 6}, allow_nil: true
  after_initialize :ensure_session_token
  
  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.is_password?(password)
    user 
  end

  def is_password?(password)
    bcrypt_password = BCrypt::Password.new(self.password_digest)
    bcrypt_password.is_password?(password)
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def reset_session_token!
    self.update!(session_token: self.class.generate_session_token)
    self.session_token
  end

end

rspec_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user 
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def ensure_logged_in 
    redirect_to new_sessions_url unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout! 
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end
end

rspec_project/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

  def new 
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:username, :password])
    if user
      login!(user)
    end
  end


end

rspec_project/app/controllers/users_controller.rb
class UsersController < ApplicationController 
  def new 
    @user = User.new 
    render :new 
  end

  def create 
    user = User.new(user_params)
    if user.save
      login!(user)
      redirect_to users_url
    else
      flash.now[:errors] = user.errors.full_messages
      render :new 
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

rspec_project/app/helpers/application_helper.rb
module ApplicationHelper
end

rspec_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RspecProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <%= "Welcome #{current_user.name}"%>
    <form action="<%=session_url%>" method="POST" >
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="logout">
    </form>

    <% else %>
    <a href="<%=new_session_url%>">Log In!</a>
    <a href="<%=new_user_url%>">Create Account</a>
    <% end %>
    <%= yield %>
  </body>
</html>

rspec_project/app/views/users/new.html.erb
<h1>Create an Account</h1>

<form action="<%=users_url%>" method="POST">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
<label for="CreateUsername">Create Username</label>
<input type="text" id="CreateUsername" name="user[username]">
<label for="CreatePassword">Create Password</label>
<input type="password" id="CreatePassword" name="user[password]">
<input type="submit" value="Create Account">
</form>